// ******************************************************************
//       /\ /|       @file       ConfigManager.cs
//       \ V/        @brief      auto generated by RabiConfigGenerator.
//       | "")       @author     Shadowrabbit, yingtu0401@gmail.com
//       /  |
//      /  \\        @Modified   2022-04-23 22:40:15
//    *(__\_\        @Copyright  Copyright (c)  2022, Shadowrabbit
// ******************************************************************

using System.Collections.Generic;
using System.IO;
using RabiConfigLib;
using RiskAndReward.Configs;
using Debug = UnityEngine.Debug;

namespace RiskAndReward
{
    public sealed class ConfigManager : BaseSingleTon<ConfigManager>
    {
        private readonly Dictionary<string, CsvReader> _cfgName2CsvReader = new(); //csvName,data
        private string? _modDirectory; // mod目录路径
        public readonly CfgLootReward cfgLootReward = new();

        /// <summary>
        /// 初始化配置管理器
        /// </summary>
        /// <param name="modDirectory">mod目录路径，从OnAfterSetup传入info.path</param>
        public void Init(string? modDirectory)
        {
            _modDirectory = modDirectory; // 保存mod目录
            LoadSource();
        }

        /// <summary>
        /// Generate configuration
        /// </summary>
        public void GenerateConfigs()
        {
            cfgLootReward.Load(_cfgName2CsvReader[nameof(CfgLootReward)]);
        }

        /// <summary>
        /// Find data source
        /// </summary>
        /// <param name="cfgName"></param>
        /// <returns></returns>
        public CsvReader? FindData(string cfgName)
        {
            if (_cfgName2CsvReader.TryGetValue(cfgName, out var data)) return data;
            Debug.LogError($"can't find data. cfgName:{cfgName}");
            return null;
        }

        /// <summary>
        /// Insert data
        /// </summary>
        /// <param name="cfgName"></param>
        /// <param name="reader"></param>
        public void InsertData(string cfgName, CsvReader reader)
        {
            if (_cfgName2CsvReader.ContainsKey(cfgName))
            {
                Debug.LogError($"repeatedly loaded table cfgName:{cfgName}");
                return;
            }

            _cfgName2CsvReader.Add(cfgName, reader);
        }

        /// <summary>
        /// 从mod目录加载Assets子目录下的所有txt文件
        /// </summary>
        private void LoadSource()
        {
            if (string.IsNullOrEmpty(_modDirectory))
            {
                Debug.LogError("mod目录路径为空，无法加载配置文件");
                return;
            }

            if (_modDirectory == null)
            {
                return;
            }

            var assetsPath = Path.Combine(_modDirectory, "Assets");
            if (!Directory.Exists(assetsPath))
            {
                Debug.LogError($"Assets目录不存在: {assetsPath}");
                return;
            }

            Debug.Log($"开始从mod目录加载配置文件: {_modDirectory}");
            var txtFiles = Directory.GetFiles(assetsPath, "*.txt", SearchOption.AllDirectories);
            foreach (var filePath in txtFiles)
            {
                try
                {
                    LoadTxtFile(filePath);
                }
                catch (System.Exception ex)
                {
                    Debug.LogError($"加载配置文件失败: {filePath}, 错误: {ex.Message}");
                }
            }

            Debug.Log($"配置文件加载完成，共加载 {txtFiles.Length} 个文件");
            GenerateConfigs();
        }

        /// <summary>
        /// 加载单个txt文件
        /// </summary>
        /// <param name="filePath">文件路径</param>
        private void LoadTxtFile(string filePath)
        {
            var fileName = Path.GetFileNameWithoutExtension(filePath);
            Debug.Log($"正在加载配置文件: {fileName}");
            var fileContent = File.ReadAllText(filePath);
            var reader = new CsvReader();
            reader.LoadText(fileContent);
            InsertData(fileName, reader);
            Debug.Log($"配置文件加载完成: {fileName}");
        }
    }
}
