// ******************************************************************
//       /\ /|       @file       DefLootReward.cs
//       \ V/        @brief      auto generated by RabiConfigGenerator. ./Excel/LootReward.xlsx
//       | "")       @author     Shadowrabbit, yingtu0401@gmail.com
//       /  |
//      /  \\        @Modified   2022-04-25 13:25:11
//    *(__\_\        @Copyright  Copyright (c)  2022, Shadowrabbit
// ******************************************************************

namespace RiskAndReward.Defs
{
    public static class DefLootReward
    {
        public static readonly string DStandard = "Standard"; 
        public static readonly string DStandardChallenge = "StandardChallenge"; 
        public static readonly string DCustom = "Custom"; 
        public static readonly string DEasy = "Easy"; 
        public static readonly string DExtraEasy = "ExtraEasy"; 
        public static readonly string DHard = "Hard"; 
        public static readonly string DExtraHard = "ExtraHard"; 
        public static readonly string DRage = "Rage"; 
    }
}